# Generated by Django 5.2.9 on 2026-01-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('area', models.IntegerField()),
                ('monthly_rent', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RENTED', 'Rented'), ('SOLD', 'Sold'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=255)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
