# Generated by Django 5.2.9 on 2026-01-13 07:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartment_monthly_rent_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffManagedApartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantRentedApartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='address',
            new_name='street_line_1',
        ),
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.CharField(default='Tokyo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='country',
            field=models.CharField(default='JP', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_apartments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='postal_code',
            field=models.CharField(default=80304, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='state',
            field=models.CharField(default='Tokyo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='street_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='apartment',
            name='unit_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='apartment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance'), ('RESERVED', 'Reserved')], default='VACANT', max_length=255),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['status'], name='apartments__status_e1091c_idx'),
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('street_line_1', 'street_line_2', 'unit_number', 'city', 'state', 'postal_code', 'country'), name='unique_address'),
        ),
        migrations.AddField(
            model_name='staffmanagedapartments',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='staffmanagedapartments',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_apartments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantrentedapartments',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_rentals', to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='tenantrentedapartments',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_apartments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='staffmanagedapartments',
            constraint=models.UniqueConstraint(fields=('apartment', 'staff'), name='unique_staff_apartment'),
        ),
        migrations.AddConstraint(
            model_name='tenantrentedapartments',
            constraint=models.UniqueConstraint(fields=('apartment', 'tenant'), name='unique_tenant_apartment'),
        ),
    ]
