# Generated by Django 5.2.9 on 2026-01-14 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_staffmanagedapartments_tenantrentedapartments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantrentedapartments',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='tenantrentedapartments',
            name='tenant',
        ),
        migrations.AddField(
            model_name='apartment',
            name='staff',
            field=models.ManyToManyField(related_name='managing_apartments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apartment',
            name='tenants',
            field=models.ManyToManyField(related_name='renting_apartments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StaffManagedApartments',
        ),
        migrations.DeleteModel(
            name='TenantRentedApartments',
        ),
    ]
